In [6]:
import numpy as np
import pandas as pd

In [9]:
lap=pd.read_csv('laptops.csv',encoding ='latin1')

In [10]:
lap.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros)
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45"
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60"

In [14]:
# creating an array based on price tiers 
np.where(pd.to_numeric (lap['Price (Euros)'],errors='coerce')>2000,'expensive','cheap')

array(['cheap', 'cheap', 'cheap', ..., 'cheap', 'cheap', 'cheap'],
      dtype='<U9')

In [15]:
# set it to a new column 
# lap ['tier']=np.where(pd.to_numeric (lap['Price (Euros)'],errors='coerce')>2000,'expensive','cheap')

In [17]:
   print(pd.to_numeric(lap['Price (Euros)'], errors='coerce').dtype)

float64

In [18]:
   print(lap['Price (Euros)'].head())
   print(pd.to_numeric(lap['Price (Euros)'], errors='coerce').head())

0    1339,69
1     898,94
2     575,00
3    2537,45
4    1803,60
Name: Price (Euros), dtype: object
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Price (Euros), dtype: float64

In [19]:
   print((pd.to_numeric(lap['Price (Euros)'], errors='coerce') > 2000).head())

0    False
1    False
2    False
3    False
4    False
Name: Price (Euros), dtype: bool

In [20]:
# Replace commas with periods and then convert to numeric
lap['tier'] = np.where(
    pd.to_numeric(lap['Price (Euros)'].str.replace(',', '.'), errors='coerce') > 2000,
    'expensive',
    'cheap'
)

In [21]:
lap.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros),tier
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69",cheap
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94",cheap
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00",cheap
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45",expensive
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60",cheap

In [1]:
# Replace commas with periods in the Price column
lap['Price (Euros)'] = lap['Price (Euros)'].str.replace(',', '.')

# Convert the column to numeric type
lap['Price (Euros)'] = pd.to_numeric(lap['Price (Euros)'], errors='coerce')

# Now create the tier column
lap['tier'] = np.where(lap['Price (Euros)'] > 2000, 'expensive', 'cheap')

NameError: name 'lap' is not defined