In [2]:
import numpy as np
import pandas as pd

In [3]:
lap=pd.read_csv('laptops.csv',encoding ='latin1')

In [8]:
lap.head(3)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros)
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"

In [10]:
# renaming price column
lap=lap.rename(columns={'Price (Euros)':'price'})

In [11]:
lap.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45"
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60"

In [17]:
lap['price']=lap['price'].str.replace(',','.')

In [20]:
lap['price']= pd.to_numeric(lap['price'])

In [23]:
lap.head(2)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,898.94

In [28]:
# creating a column based on price
np.where(lap['price']>1000,"expensive","Affordable")

array(['expensive', 'Affordable', 'Affordable', ..., 'Affordable',
       'Affordable', 'Affordable'], dtype='<U10')

In [26]:
lap['status']=np.where(lap['price']>1000,"expensive","Affordable")

In [27]:
lap.head(2)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price,status
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69,expensive
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,898.94,Affordable

In [29]:
# find apple laptops that costs more than 1000
(lap['price']>1000)&(lap['Manufacturer']=='Apple')

0        True
1       False
2       False
3        True
4        True
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Length: 1303, dtype: bool

In [71]:
lap[(lap['price']>1000)&(lap['Manufacturer']=='Apple')]

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price,status,report
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69,expensive,Affordable
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,898.94,Affordable,Cheap

In [33]:
lap['Screen Size'].str.replace('"','')

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1298    14.0
1299    13.3
1300    14.0
1301    15.6
1302    15.6
Name: Screen Size, Length: 1303, dtype: object

In [34]:
lap['Screen Size']=lap['Screen Size'].str.replace('"','')

In [35]:
lap.head(3)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price,status
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69,expensive
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,898.94,Affordable
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,575.00,Affordable

In [ ]:
# creating a conditional column from more than 2 choices : np.seleect()

In [36]:
# create an array based on multiple price tiers (+2 choices)

In [72]:
# create  'conditions ' and 'values' variables 

conditions=[
    lap['price']>2000,
    (lap['price']<=2000)&(lap['price']>1500),
    (lap['price']<=1500)&(lap['price']>1000),
    (lap['price']<=1000)
]
values=['Too Expensive','Expensive','Affordable','Cheap']

In [55]:
# set it to a column
np.select(conditions,values)

array(['Affordable', 'Cheap', 'Cheap', ..., 'Cheap', 'Cheap', 'Cheap'],
      dtype='<U13')

In [41]:
lap['report']=np.select(conditions,values)

In [44]:
lap['price'].value_counts

<bound method IndexOpsMixin.value_counts of 0       1339.69
1        898.94
2        575.00
3       2537.45
4       1803.60
         ...
1298     638.00
1299    1499.00
1300     229.00
1301     764.00
1302     369.00
Name: price, Length: 1303, dtype: float64>

In [64]:

# exercise
# do it for screen size 
lap['Screen Size']= pd.to_numeric(lap['Screen Size'])

In [73]:
condition=[
    (lap['Screen Size']>=13),
    (lap['Screen Size']>=10)&( lap['Screen Size']<13),
    (lap['Screen Size']<10)
]
value=['Large','Medium','Smol']

In [74]:
np.select(condition,value)

array(['Large', 'Large', 'Large', ..., 'Large', 'Large', 'Large'],
      dtype='<U6')

In [75]:
lap['Screen Status']=np.select(condition,value)

In [76]:
lap.head(2)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price,status,report,Screen Status
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69,expensive,Affordable,Large
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,898.94,Affordable,Cheap,Large

In [77]:
lap['Screen Status'].value_counts

<bound method IndexOpsMixin.value_counts of 0       Large
1       Large
2       Large
3       Large
4       Large
        ...
1298    Large
1299    Large
1300    Large
1301    Large
1302    Large
Name: Screen Status, Length: 1303, dtype: object>