In [1]:
import numpy as np
import pandas as pd

In [2]:
report =pd.read_csv('file.csv')

In [3]:
report.head(2)

   Unnamed: 0   Student Name Exam Name        Date  Points
0         NaN  Vaibhav Kumar   Biology  05/06/2016   100.0
1         NaN  Velma Clemons   Biology  05/06/2016    43.0

In [4]:
report.drop('Unnamed: 0',axis=1)

         Student Name Exam Name        Date  Points
0       Vaibhav Kumar   Biology  05/06/2016   100.0
1       Velma Clemons   Biology  05/06/2016    43.0
2          kelly frye   Biology  05/06/2016    81.0
3         Louis Mcgee   Biology  05/06/2016    11.0
4        Phyllis Paul   Biology  05/06/2016    18.0
5      Zenaida Decker   Biology  05/06/2016    55.0
6     Gillian Tillman   Biology  05/06/2016    38.0
7     Constance Boone   Biology  05/06/2016    16.0
8   Giselle Lancaster   Biology  05/06/2016    73.0
9    Kirsten Mcdowell   Biology  05/06/2016    16.0
10                NaN       NaN         NaN     NaN
11                NaN       NaN         NaN     NaN
12         21/06/2025       NaN         NaN     NaN

In [5]:
report.rename(columns={report.columns[0]:'Index'},inplace=True)

In [6]:
p=np.arange(1,14)

In [7]:
report['Index']=p

In [8]:
report.head()

   Index   Student Name Exam Name        Date  Points
0      1  Vaibhav Kumar   Biology  05/06/2016   100.0
1      2  Velma Clemons   Biology  05/06/2016    43.0
2      3     kelly frye   Biology  05/06/2016    81.0
3      4    Louis Mcgee   Biology  05/06/2016    11.0
4      5   Phyllis Paul   Biology  05/06/2016    18.0

In [9]:
report.set_index('Index',inplace=True)

In [10]:
report

            Student Name Exam Name        Date  Points
Index
1          Vaibhav Kumar   Biology  05/06/2016   100.0
2          Velma Clemons   Biology  05/06/2016    43.0
3             kelly frye   Biology  05/06/2016    81.0
4            Louis Mcgee   Biology  05/06/2016    11.0
5           Phyllis Paul   Biology  05/06/2016    18.0
6         Zenaida Decker   Biology  05/06/2016    55.0
7        Gillian Tillman   Biology  05/06/2016    38.0
8        Constance Boone   Biology  05/06/2016    16.0
9      Giselle Lancaster   Biology  05/06/2016    73.0
10      Kirsten Mcdowell   Biology  05/06/2016    16.0
11                   NaN       NaN         NaN     NaN
12                   NaN       NaN         NaN     NaN
13            21/06/2025       NaN         NaN     NaN

In [11]:
# find duplicates in 1 column /series

In [12]:
report.duplicated('Student Name')

Index
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
dtype: bool

In [13]:
report[report.duplicated('Student Name')]# shows the duplicated rows

      Student Name Exam Name Date  Points
Index
12             NaN       NaN  NaN     NaN

In [14]:
dup=report.duplicated(['Student Name','Points','Date'])

In [15]:
report[dup].sort_values(['Student Name'])

      Student Name Exam Name Date  Points
Index
12             NaN       NaN  NaN     NaN

In [18]:

report.duplicated('Date')

Index
1     False
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11    False
12     True
13     True
dtype: bool