In [3]:
import pandas as pd
import numpy as np

In [14]:
df=pd.read_csv('file.csv')
del df['Unnamed: 0']
df=df.set_index('Student Name')
import random 
point1=[random.randint(150,180)for _ in range(13)]
df.rename(columns={'Points':'Marks'},inplace=True)
df['Height']=point1

1 Selecting with a single value

iloc[row_positionl,column_position]

In [38]:
#get the 
df

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     155
Velma Clemons       Biology  05/06/2016   43.0     179
kelly frye          Biology  05/06/2016   81.0     152
Louis Mcgee         Biology  05/06/2016   11.0     180
Phyllis Paul        Biology  05/06/2016   18.0     177
Zenaida Decker      Biology  05/06/2016   55.0     175
Gillian Tillman     Biology  05/06/2016   38.0     174
Constance Boone     Biology  05/06/2016   16.0     151
Giselle Lancaster   Biology  05/06/2016   73.0     175
Kirsten Mcdowell    Biology  05/06/2016   16.0     152
NaN                     NaN         NaN    NaN     160
NaN                     NaN         NaN    NaN     180
21/06/2025              NaN         NaN    NaN     160

In [37]:
# get the height of Vaibhav Kumar

In [36]:
df.iloc[0,3]

155

In [39]:
# height of kelly frye

In [40]:
df.iloc[2,3]

152

In [41]:
# get all rows inside the 'Height' column

In [44]:
df.iloc[:,3]

Student Name
Vaibhav Kumar        155
Velma Clemons        179
kelly frye           152
Louis Mcgee          180
Phyllis Paul         177
Zenaida Decker       175
Gillian Tillman      174
Constance Boone      151
Giselle Lancaster    175
Kirsten Mcdowell     152
NaN                  160
NaN                  180
21/06/2025           160
Name: Height, dtype: int64

In [48]:
# get all the column correspond to kelly frye
df.iloc[2,:]

Exam Name       Biology
Date         05/06/2016
Marks              81.0
Height              152
Name: kelly frye, dtype: object

2 Selecting with a list of values

In [58]:
# get all data about Vaibhav Kumar and kelly frye

df.iloc [[0,2,4]]

              Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar   Biology  05/06/2016  100.0     155
kelly frye      Biology  05/06/2016   81.0     152
Phyllis Paul    Biology  05/06/2016   18.0     177

In [59]:
# get the height of vaibhav and kelly 
df.iloc[[0,2],3]

Student Name
Vaibhav Kumar    155
kelly frye       152
Name: Height, dtype: int64

In [61]:
# get the height and marks of vaibhav 
df.iloc[[0,2],[2,3]]

               Marks  Height
Student Name
Vaibhav Kumar  100.0     155
kelly frye      81.0     152

3 Selecting a range of data with a slice

start:stop(start is included and stop is excluded )

In [69]:
# slice column labels Marks/Height
# students =['Vaibhav Kumar','kelly frye']

df.iloc[[0,2],1:4]

                     Date  Marks  Height
Student Name
Vaibhav Kumar  05/06/2016  100.0     155
kelly frye     05/06/2016   81.0     152

In [71]:
# same as above
std=[0,2]
df.iloc[std,2:4]

               Marks  Height
Student Name
Vaibhav Kumar  100.0     155
kelly frye      81.0     152

In [72]:
# slice index labels (top1 to top5 students)
# columns=['Marks','Height']
col=[2,3]
df.iloc[0:6,col]

                Marks  Height
Student Name
Vaibhav Kumar   100.0     155
Velma Clemons    43.0     179
kelly frye       81.0     152
Louis Mcgee      11.0     180
Phyllis Paul     18.0     177
Zenaida Decker   55.0     175

4 Selecting with conditions

iloc cannot accept a boolean Series , but only a boolean list .We have to 
use the list() function to convert a Series into a boolean list

In [79]:
# one condition : select student with height above 170cm

col=[2,3]
k=list(df['Height']>=170)
df.iloc[k,col]

                   Marks  Height
Student Name
Velma Clemons       43.0     179
Louis Mcgee         11.0     180
Phyllis Paul        18.0     177
Zenaida Decker      55.0     175
Gillian Tillman     38.0     174
Giselle Lancaster   73.0     175
NaN                  NaN     180

In [104]:
# multiple conditions : select player with height above 160cm and Marks >60
col=[1,2]


df.iloc[list((df['Marks']>50)&(df['Height']>150)),:]

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     155
kelly frye          Biology  05/06/2016   81.0     152
Zenaida Decker      Biology  05/06/2016   55.0     175
Giselle Lancaster   Biology  05/06/2016   73.0     175