In [1]:
import pandas as pd 
import numpy as np

df=pd.read_csv('file.csv')
del df['Unnamed: 0']
df=df.set_index('Student Name')
import random 
point1=[random.randint(150,180)for _ in range(13)]
df.rename(columns={'Points':'Marks'},inplace=True)
df['Height']=point1

df=df.dropna()# delete rows with any NaN values

In [2]:
df.head()

              Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar   Biology  05/06/2016  100.0     151
Velma Clemons   Biology  05/06/2016   43.0     173
kelly frye      Biology  05/06/2016   81.0     160
Louis Mcgee     Biology  05/06/2016   11.0     165
Phyllis Paul    Biology  05/06/2016   18.0     166

1 Set value to one cell

In [4]:
# update vaibhav's height 
df.loc['Vaibhav Kumar','Height']=175

In [5]:
df.head(1)

              Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar   Biology  05/06/2016  100.0     175

2 Set value to entire column

In [7]:
df.loc[:,'Height']

Student Name
Vaibhav Kumar        175
Velma Clemons        173
kelly frye           160
Louis Mcgee          165
Phyllis Paul         166
Zenaida Decker       156
Gillian Tillman      180
Constance Boone      172
Giselle Lancaster    160
Kirsten Mcdowell     179
NaN                  166
NaN                  157
21/06/2025           160
Name: Height, dtype: int64

In [8]:
df.loc[:,'Height']=176

In [10]:
df

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     176
Velma Clemons       Biology  05/06/2016   43.0     176
kelly frye          Biology  05/06/2016   81.0     176
Louis Mcgee         Biology  05/06/2016   11.0     176
Phyllis Paul        Biology  05/06/2016   18.0     176
Zenaida Decker      Biology  05/06/2016   55.0     176
Gillian Tillman     Biology  05/06/2016   38.0     176
Constance Boone     Biology  05/06/2016   16.0     176
Giselle Lancaster   Biology  05/06/2016   73.0     176
Kirsten Mcdowell    Biology  05/06/2016   16.0     176
NaN                     NaN         NaN    NaN     176
NaN                     NaN         NaN    NaN     176
21/06/2025              NaN         NaN    NaN     176

3 Set valure to entire row

In [16]:
# get all columns that corresponds to student ranked last 
df.iloc[9,:] # or [-1,:]

Exam Name       Biology
Date         05/06/2016
Marks              16.0
Height              176
Name: Kirsten Mcdowell, dtype: object

In [27]:
df.iloc[-1:]

                 Exam Name        Date  Marks  Height
Student Name
Kirsten Mcdowell   Biology  05/06/2016   16.0     176

4 Set value to multiple cells

In [30]:
# set values for all items matching the list of lebels
df.loc[['Vaibhav Kumar','kelly frye'],['Height']] =177

In [31]:
df.head(4)

              Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar   Biology  05/06/2016  100.0     177
Velma Clemons   Biology  05/06/2016   43.0     176
kelly frye      Biology  05/06/2016   81.0     177
Louis Mcgee     Biology  05/06/2016   11.0     176

5 Set value for rows matching a condition

In [36]:
# set value for rows matching a condition
col=['Exam Name','Marks']

df.loc[df['Marks']>55,col]# =0 to change all data to 0

                  Exam Name  Marks
Student Name
Vaibhav Kumar       Biology  100.0
kelly frye          Biology   81.0
Giselle Lancaster   Biology   73.0