In [2]:
import pandas as pd 
import numpy as np

df=pd.read_csv('file.csv')
del df['Unnamed: 0']
df=df.set_index('Student Name')
import random 
point1=[random.randint(150,180)for _ in range(13)]
df.rename(columns={'Points':'Marks'},inplace=True)
df['Height']=point1

df=df.dropna()# delete rows with any NaN values

1 Drop Row

In [3]:
df

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     154
Velma Clemons       Biology  05/06/2016   43.0     178
kelly frye          Biology  05/06/2016   81.0     172
Louis Mcgee         Biology  05/06/2016   11.0     177
Phyllis Paul        Biology  05/06/2016   18.0     171
Zenaida Decker      Biology  05/06/2016   55.0     174
Gillian Tillman     Biology  05/06/2016   38.0     158
Constance Boone     Biology  05/06/2016   16.0     173
Giselle Lancaster   Biology  05/06/2016   73.0     161
Kirsten Mcdowell    Biology  05/06/2016   16.0     177

In [4]:
# drop one row
# 1 axis parameter 
df.drop('Kirsten Mcdowell',axis=0)# 0 for row and 1 for column

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     154
Velma Clemons       Biology  05/06/2016   43.0     178
kelly frye          Biology  05/06/2016   81.0     172
Louis Mcgee         Biology  05/06/2016   11.0     177
Phyllis Paul        Biology  05/06/2016   18.0     171
Zenaida Decker      Biology  05/06/2016   55.0     174
Gillian Tillman     Biology  05/06/2016   38.0     158
Constance Boone     Biology  05/06/2016   16.0     173
Giselle Lancaster   Biology  05/06/2016   73.0     161

In [7]:
# 2 index parameter
df.drop(index=['Kirsten Mcdowell'])# same as above

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     154
Velma Clemons       Biology  05/06/2016   43.0     178
kelly frye          Biology  05/06/2016   81.0     172
Louis Mcgee         Biology  05/06/2016   11.0     177
Phyllis Paul        Biology  05/06/2016   18.0     171
Zenaida Decker      Biology  05/06/2016   55.0     174
Gillian Tillman     Biology  05/06/2016   38.0     158
Constance Boone     Biology  05/06/2016   16.0     173
Giselle Lancaster   Biology  05/06/2016   73.0     161

In [8]:
# drop two or more rows and update data (inplace =True)
df.drop(['Vaibhav Kumar','kelly frye'],axis=0)

                  Exam Name        Date  Marks  Height
Student Name
Velma Clemons       Biology  05/06/2016   43.0     178
Louis Mcgee         Biology  05/06/2016   11.0     177
Phyllis Paul        Biology  05/06/2016   18.0     171
Zenaida Decker      Biology  05/06/2016   55.0     174
Gillian Tillman     Biology  05/06/2016   38.0     158
Constance Boone     Biology  05/06/2016   16.0     173
Giselle Lancaster   Biology  05/06/2016   73.0     161
Kirsten Mcdowell    Biology  05/06/2016   16.0     177

2 Drop Column

In [17]:
# drop one column
#1 axis parameter 
df.drop('Exam Name',axis=1)
# df.drop(columns=['Exam Name']) same as above

                         Date  Marks  Height
Student Name
Vaibhav Kumar      05/06/2016  100.0     154
Velma Clemons      05/06/2016   43.0     178
kelly frye         05/06/2016   81.0     172
Louis Mcgee        05/06/2016   11.0     177
Phyllis Paul       05/06/2016   18.0     171
Zenaida Decker     05/06/2016   55.0     174
Gillian Tillman    05/06/2016   38.0     158
Constance Boone    05/06/2016   16.0     173
Giselle Lancaster  05/06/2016   73.0     161
Kirsten Mcdowell   05/06/2016   16.0     177

In [23]:
# drop columns by position/index (drop last column)
# df.columns[[-1]]
df.drop(df.columns[[2]],axis=1)

                  Exam Name        Date  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016     154
Velma Clemons       Biology  05/06/2016     178
kelly frye          Biology  05/06/2016     172
Louis Mcgee         Biology  05/06/2016     177
Phyllis Paul        Biology  05/06/2016     171
Zenaida Decker      Biology  05/06/2016     174
Gillian Tillman     Biology  05/06/2016     158
Constance Boone     Biology  05/06/2016     173
Giselle Lancaster   Biology  05/06/2016     161
Kirsten Mcdowell    Biology  05/06/2016     177

In [25]:
# drop two or more columns 
df.drop(['Exam Name','Height'],axis=1)

                         Date  Marks
Student Name
Vaibhav Kumar      05/06/2016  100.0
Velma Clemons      05/06/2016   43.0
kelly frye         05/06/2016   81.0
Louis Mcgee        05/06/2016   11.0
Phyllis Paul       05/06/2016   18.0
Zenaida Decker     05/06/2016   55.0
Gillian Tillman    05/06/2016   38.0
Constance Boone    05/06/2016   16.0
Giselle Lancaster  05/06/2016   73.0
Kirsten Mcdowell   05/06/2016   16.0