In [1]:
import pandas as pd 
import numpy as np

df=pd.read_csv('file.csv')
del df['Unnamed: 0']
df=df.set_index('Student Name')
import random 
point1=[random.randint(150,180)for _ in range(13)]
df.rename(columns={'Points':'Marks'},inplace=True)
df['Height']=point1

df=df.dropna()# delete rows with any NaN values

In [2]:
df.head(2)

              Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar   Biology  05/06/2016  100.0     150
Velma Clemons   Biology  05/06/2016   43.0     172

1 query

In [3]:
# select students with Marks greater than 55
df.query ('Marks>55')

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     150
kelly frye          Biology  05/06/2016   81.0     175
Giselle Lancaster   Biology  05/06/2016   73.0     172

In [4]:
# the equivalent boolean slicing 
df[df['Marks']>55]

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     150
kelly frye          Biology  05/06/2016   81.0     175
Giselle Lancaster   Biology  05/06/2016   73.0     172

In [7]:
# with multiple conditions
df.query('Marks>40 and Height>150')# or &

                  Exam Name        Date  Marks  Height
Student Name
Velma Clemons       Biology  05/06/2016   43.0     172
kelly frye          Biology  05/06/2016   81.0     175
Zenaida Decker      Biology  05/06/2016   55.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     172

In [8]:
df[(df['Marks']>40)&(df['Height']>150)]

                  Exam Name        Date  Marks  Height
Student Name
Velma Clemons       Biology  05/06/2016   43.0     172
kelly frye          Biology  05/06/2016   81.0     175
Zenaida Decker      Biology  05/06/2016   55.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     172

In [12]:
df.query("not(Marks>60)") # with a not condition|

                 Exam Name        Date  Marks  Height
Student Name
Velma Clemons      Biology  05/06/2016   43.0     172
Louis Mcgee        Biology  05/06/2016   11.0     170
Phyllis Paul       Biology  05/06/2016   18.0     162
Zenaida Decker     Biology  05/06/2016   55.0     152
Gillian Tillman    Biology  05/06/2016   38.0     160
Constance Boone    Biology  05/06/2016   16.0     173
Kirsten Mcdowell   Biology  05/06/2016   16.0     154

In [17]:
#equivalent booleajn slicing of above 
df[~(df['Marks']>40)]

                 Exam Name        Date  Marks  Height
Student Name
Louis Mcgee        Biology  05/06/2016   11.0     170
Phyllis Paul       Biology  05/06/2016   18.0     162
Gillian Tillman    Biology  05/06/2016   38.0     160
Constance Boone    Biology  05/06/2016   16.0     173
Kirsten Mcdowell   Biology  05/06/2016   16.0     154

In [18]:
# convert height to meters and select those with height above 1.6 meter
df.query('Height/100>1.6')

                  Exam Name        Date  Marks  Height
Student Name
Velma Clemons       Biology  05/06/2016   43.0     172
kelly frye          Biology  05/06/2016   81.0     175
Louis Mcgee         Biology  05/06/2016   11.0     170
Phyllis Paul        Biology  05/06/2016   18.0     162
Constance Boone     Biology  05/06/2016   16.0     173
Giselle Lancaster   Biology  05/06/2016   73.0     172

In [29]:
# check the data types 
df.dtypes
# conver 'Date' column to date time type
df['Date'] =df['Date'].astype('datetime64[ns]')
df['Date'].dt.year

Student Name
Vaibhav Kumar        2016
Velma Clemons        2016
kelly frye           2016
Louis Mcgee          2016
Phyllis Paul         2016
Zenaida Decker       2016
Gillian Tillman      2016
Constance Boone      2016
Giselle Lancaster    2016
Kirsten Mcdowell     2016
Name: Date, dtype: int32

In [32]:
df.query('Date.dt.year==2016')

                  Exam Name       Date  Marks  Height
Student Name
Vaibhav Kumar       Biology 2016-05-06  100.0     150
Velma Clemons       Biology 2016-05-06   43.0     172
kelly frye          Biology 2016-05-06   81.0     175
Louis Mcgee         Biology 2016-05-06   11.0     170
Phyllis Paul        Biology 2016-05-06   18.0     162
Zenaida Decker      Biology 2016-05-06   55.0     152
Gillian Tillman     Biology 2016-05-06   38.0     160
Constance Boone     Biology 2016-05-06   16.0     173
Giselle Lancaster   Biology 2016-05-06   73.0     172
Kirsten Mcdowell    Biology 2016-05-06   16.0     154

In [ ]:

# select students with marks more than 50