In [1]:
import pandas as pd 
import numpy as np

df=pd.read_csv('file.csv')
del df['Unnamed: 0']
df=df.set_index('Student Name')
import random 
point1=[random.randint(150,180)for _ in range(13)]
df.rename(columns={'Points':'Marks'},inplace=True)
df['Height']=point1

df=df.dropna()# delete rows with any NaN values

1 Copy()

1.1 deep =True

In [6]:
# deep = True by default ( Modifications to the data or indices of the copy )
df_copy=df.copy()

In [8]:
# update value in original dataframe 
df.loc['Vaibhav Kumar','Height']=170

In [9]:
df

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     170
Velma Clemons       Biology  05/06/2016   43.0     174
kelly frye          Biology  05/06/2016   81.0     168
Louis Mcgee         Biology  05/06/2016   11.0     152
Phyllis Paul        Biology  05/06/2016   18.0     151
Zenaida Decker      Biology  05/06/2016   55.0     180
Gillian Tillman     Biology  05/06/2016   38.0     166
Constance Boone     Biology  05/06/2016   16.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     162
Kirsten Mcdowell    Biology  05/06/2016   16.0     165

In [10]:
df_copy

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     159
Velma Clemons       Biology  05/06/2016   43.0     174
kelly frye          Biology  05/06/2016   81.0     168
Louis Mcgee         Biology  05/06/2016   11.0     152
Phyllis Paul        Biology  05/06/2016   18.0     151
Zenaida Decker      Biology  05/06/2016   55.0     180
Gillian Tillman     Biology  05/06/2016   38.0     166
Constance Boone     Biology  05/06/2016   16.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     162
Kirsten Mcdowell    Biology  05/06/2016   16.0     165

1.2 deep =False

In [16]:
# deep = False ( Any changes to the data of the original will be reflected )
df_s_copy=df.copy(deep=False)# its called shallow copy

In [17]:
df.loc['Vaibhav Kumar','Height']=190

In [18]:
df

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     190
Velma Clemons       Biology  05/06/2016   43.0     174
kelly frye          Biology  05/06/2016   81.0     168
Louis Mcgee         Biology  05/06/2016   11.0     152
Phyllis Paul        Biology  05/06/2016   18.0     151
Zenaida Decker      Biology  05/06/2016   55.0     180
Gillian Tillman     Biology  05/06/2016   38.0     166
Constance Boone     Biology  05/06/2016   16.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     162
Kirsten Mcdowell    Biology  05/06/2016   16.0     165

In [19]:
df_s_copy

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     190
Velma Clemons       Biology  05/06/2016   43.0     174
kelly frye          Biology  05/06/2016   81.0     168
Louis Mcgee         Biology  05/06/2016   11.0     152
Phyllis Paul        Biology  05/06/2016   18.0     151
Zenaida Decker      Biology  05/06/2016   55.0     180
Gillian Tillman     Biology  05/06/2016   38.0     166
Constance Boone     Biology  05/06/2016   16.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     162
Kirsten Mcdowell    Biology  05/06/2016   16.0     165

1.3 Simple assignment

In [25]:
# make a copy
df_new_copy=df# same as shallow copy

In [22]:
df.loc['Vaibhav Kumar','Height']=200

In [23]:
df

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     200
Velma Clemons       Biology  05/06/2016   43.0     174
kelly frye          Biology  05/06/2016   81.0     168
Louis Mcgee         Biology  05/06/2016   11.0     152
Phyllis Paul        Biology  05/06/2016   18.0     151
Zenaida Decker      Biology  05/06/2016   55.0     180
Gillian Tillman     Biology  05/06/2016   38.0     166
Constance Boone     Biology  05/06/2016   16.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     162
Kirsten Mcdowell    Biology  05/06/2016   16.0     165

In [24]:
df_new_copy

                  Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar       Biology  05/06/2016  100.0     200
Velma Clemons       Biology  05/06/2016   43.0     174
kelly frye          Biology  05/06/2016   81.0     168
Louis Mcgee         Biology  05/06/2016   11.0     152
Phyllis Paul        Biology  05/06/2016   18.0     151
Zenaida Decker      Biology  05/06/2016   55.0     180
Gillian Tillman     Biology  05/06/2016   38.0     166
Constance Boone     Biology  05/06/2016   16.0     152
Giselle Lancaster   Biology  05/06/2016   73.0     162
Kirsten Mcdowell    Biology  05/06/2016   16.0     165