In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Car_sales.csv')

In [3]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [4]:
df=df[['Manufacturer','Sales_in_thousands','Vehicle_type','Price_in_thousands','Horsepower','Fuel_capacity']]

In [5]:
df.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Horsepower             66
Fuel_capacity          55
dtype: int64

1 agg()

In [6]:
# calculate the sum of columns 
df.agg('sum')

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [7]:
# calculate the mean of numeric columns
df.select_dtypes(include=['number']).agg('mean')

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [8]:
# calculate the mean and count values
df.apply(['sum','count'])

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
sum,AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...,8320.698,PassengerPassengerPassengerPassengerPassengerP...,4245.567,29008.0,2800.5
count,157,157.000,157,155.000,156.0,156.0

In [9]:
# different aggregation per column : calculate the sum and mean of 'sales '
df.agg({'Sales_in_thousands':['sum','mean'],
        'Price_in_thousands':['sum','max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [10]:
# aggregate over the columns 
df[['Sales_in_thousands','Price_in_thousands']].agg('sum',axis=1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [11]:
df['Sales_in_thousands']+df['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [12]:
df.agg(x_sum=('Sales_in_thousands','sum'),
      y_mean=('Sales_in_thousands','mean'))

        Sales_in_thousands
x_sum          8320.698000
y_mean           52.998076

2 The split-apply combine strategy

In [15]:
# split data into separate groups 
passenger_filter =df['Vehicle_type']=='passanger'
car_filter=df['Vehicle_type']=='Car'
df['Vehicle_type'].value_counts()

Vehicle_type
Passanger    157
Name: count, dtype: int64

In [22]:
# apply an operation
df[passanger_filter]['Sales_in_thousands'].mean()

NameError: name 'passanger_filter' is not defined