In [1]:
import pandas as pd
import numpy as np

1 Concat()

1.1 Concatenate vertically

In [17]:
df1=pd.DataFrame({'id':['A','B','C','D'],
                 'value':[1,2,3,4]})
df2=pd.DataFrame({'id':['D','E','F'],
                 'value':[4,5,6]})

In [18]:
pd.concat([df1,df2],axis=0,ignore_index=True)# axis=0 : vertical concatenation
# ignoreindex ignores the

  id  value
0  A      1
1  B      2
2  C      3
3  D      4
4  D      4
5  E      5
6  F      6

In [19]:
pd.concat([df1,df2],axis=1)# concatenating horizontally

  id  value   id  value
0  A      1    D    4.0
1  B      2    E    5.0
2  C      3    F    6.0
3  D      4  NaN    NaN

1 Inner join

In [23]:
df1.merge(df2,on='id',how='inner')

  id  value_x  value_y
0  D        4        4

In [27]:
df1.merge(df2,on='id',how='outer')# full join

  id  value_x  value_y
0  A      1.0      NaN
1  B      2.0      NaN
2  C      3.0      NaN
3  D      4.0      4.0
4  E      NaN      5.0
5  F      NaN      6.0

In [29]:
df2.merge(df1,on='id',how='inner')

  id  value_x  value_y
0  D        4        4

2 Full join(Exclusive)

In [32]:
# indicator =true
df1.merge(df2,on='id',how='outer',indicator=True)

  id  value_x  value_y      _merge
0  A      1.0      NaN   left_only
1  B      2.0      NaN   left_only
2  C      3.0      NaN   left_only
3  D      4.0      4.0        both
4  E      NaN      5.0  right_only
5  F      NaN      6.0  right_only

In [35]:
# Query
df1.merge(df2,on='id',how='outer',indicator=True).query("_merge=='both'")

  id  value_x  value_y _merge
3  D      4.0      4.0   both

In [37]:

df1.merge(df2,on='id',how='outer',indicator=True).query("_merge=='left_only'or _merge=='right_only'")

  id  value_x  value_y      _merge
0  A      1.0      NaN   left_only
1  B      2.0      NaN   left_only
2  C      3.0      NaN   left_only
4  E      NaN      5.0  right_only
5  F      NaN      6.0  right_only

Left join

In [39]:
df1.merge(df2,on='id',how='left',indicator=True)

  id  value_x  value_y     _merge
0  A        1      NaN  left_only
1  B        2      NaN  left_only
2  C        3      NaN  left_only
3  D        4      4.0       both

Right join

In [40]:
df1.merge(df2,on='id',how='right',indicator=True)

  id  value_x  value_y      _merge
0  D      4.0        4        both
1  E      NaN        5  right_only
2  F      NaN        6  right_only

In [47]:
#extract 50% from merged df1 and df2
merged=pd.concat([df1,df2],axis=0)

In [48]:
merged.sample(frac=0.5)

  id  value
1  E      5
2  C      3
2  F      6
0  D      4

Left join (Exclusive) {only in df1 }

In [51]:
df1.merge(df2,on='id',how='outer',indicator=True)

  id  value_x  value_y      _merge
0  A      1.0      NaN   left_only
1  B      2.0      NaN   left_only
2  C      3.0      NaN   left_only
3  D      4.0      4.0        both
4  E      NaN      5.0  right_only
5  F      NaN      6.0  right_only

In [54]:
# data exclusive to df1
df1.merge(df2,on='id',how='outer',
          indicator=True).query ("_merge=='left_only'")

  id  value_x  value_y     _merge
0  A      1.0      NaN  left_only
1  B      2.0      NaN  left_only
2  C      3.0      NaN  left_only