1 Vertical concatenation

In [1]:
import numpy as np 
import pandas as pd

In [2]:
movies=pd.read_csv('IMDb movies.csv',low_memory =False)
ratings=pd.read_csv('IMDb ratings.csv')

In [3]:
movies.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [4]:
movies=movies[['imdb_title_id', 'title', 'year','genre','country']]

In [5]:
ratings.columns

Index(['imdb_title_id', 'weighted_average_vote', 'total_votes', 'mean_vote',
       'median_vote', 'votes_10', 'votes_9', 'votes_8', 'votes_7', 'votes_6',
       'votes_5', 'votes_4', 'votes_3', 'votes_2', 'votes_1',
       'allgenders_0age_avg_vote', 'allgenders_0age_votes',
       'allgenders_18age_avg_vote', 'allgenders_18age_votes',
       'allgenders_30age_avg_vote', 'allgenders_30age_votes',
       'allgenders_45age_avg_vote', 'allgenders_45age_votes',
       'males_allages_avg_vote', 'males_allages_votes', 'males_0age_avg_vote',
       'males_0age_votes', 'males_18age_avg_vote', 'males_18age_votes',
       'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote',
       'males_45age_votes', 'females_allages_avg_vote',
       'females_allages_votes', 'females_0age_avg_vote', 'females_0age_votes',
       'females_18age_avg_vote', 'females_18age_votes',
       'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes'],
      dtype='object')

In [6]:
ratings=ratings[['imdb_title_id','total_votes','mean_vote']]

In [7]:
movies.head()

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy

In [8]:
ratings.head()

  imdb_title_id  total_votes  mean_vote
0     tt0000009          154        5.9
1     tt0000574          589        6.3
2     tt0001892          188        6.0
3     tt0002101          446        5.3
4     tt0002130         2237        6.9

1 Exercise

In [9]:
# extract a 50% sample of the original dataframe (movies)
movies['imdb_title_id'].frac=0.5

In [10]:
h_movies=movies.sample(frac=0.5)

In [11]:
h_movies.shape
movies.shape

(85855, 5)

In [12]:
#concatenate both h_movies and ratings vertically
cat=pd.concat([movies,h_movies],axis=0)

In [13]:
cat.shape

(128783, 5)

In [14]:
cat

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
37070,tt0221563,Sorted,2000,Thriller,"UK, USA"
29502,tt0115638,L'insolente,1996,"Adventure, Comedy, History",France
70282,tt3199006,Must alpinist,2015,"Adventure, Mystery, Thriller",Estonia
10173,tt0053417,Vi er allesammen tossede,1959,Comedy,Denmark
51289,tt0897249,Cumbia callera,2007,"Crime, Drama, Musical",Mexico

In [15]:
cat.set_index(['imdb_title_id'])

,title,year,genre,country
imdb_title_id,,,,
tt0000009,Miss Jerry,1894,Romance,USA
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
tt0002101,Cleopatra,1912,"Drama, History",USA
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...
tt0221563,Sorted,2000,Thriller,"UK, USA"
tt0115638,L'insolente,1996,"Adventure, Comedy, History",France
tt3199006,Must alpinist,2015,"Adventure, Mystery, Thriller",Estonia
tt0053417,Vi er allesammen tossede,1959,Comedy,Denmark
tt0897249,Cumbia callera,2007,"Crime, Drama, Musical",Mexico

In [16]:
# concatenating movies and rating based on id
movies.merge(ratings,on='imdb_title_id',
             how='outer',indicator=True)

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

Exercises

In [17]:
# 1 make a copy of the df_movies dataframe
c=movies.copy()

In [24]:
# set the first 1000 values of 'imdb_title_id' column as !tt12
# merge df_movies and df_ratings (exclusive left join)
movies.merge(ratings,on='imdb_title_id',how='left',indicator=True).query('_merge=="left_only"')

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

In [25]:
c.head()

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy

In [30]:
c.loc[0,'imdb_title_id']

'tt0000009'

In [32]:
# set the first values of c in imdb_title_id as fuck
for index in c.index :
    if index<1000:
        c.loc[index,'imdb_title_id']='fvck'

In [34]:
c.head()

,imdb_title_id,title,year,genre,country
0,fvck,Miss Jerry,1894,Romance,USA
1,fvck,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,fvck,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,fvck,Cleopatra,1912,"Drama, History",USA
4,fvck,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy

In [27]:
c['imdb_title_id']

0        tt0000009
1        tt0000574
2        tt0001892
3        tt0002101
4        tt0002130
           ...
85850    tt9908390
85851    tt9911196
85852    tt9911774
85853    tt9914286
85854    tt9914942
Name: imdb_title_id, Length: 85855, dtype: object

In [36]:
movies.merge(c,on='imdb_title_id',how='outer')

,imdb_title_id,title_x,year_x,genre_x,country_x,title_y,year_y,genre_y,country_y
0,fvck,NaN,NaN,NaN,NaN,Miss Jerry,1894,Romance,USA
1,fvck,NaN,NaN,NaN,NaN,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,fvck,NaN,NaN,NaN,NaN,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,fvck,NaN,NaN,NaN,NaN,Cleopatra,1912,"Drama, History",USA
4,fvck,NaN,NaN,NaN,NaN,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...,...,...,...,...
86850,tt9908390,Le lion,2020,Comedy,"France, Belgium",Le lion,2020,Comedy,"France, Belgium"
86851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
86852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,Padmavyuhathile Abhimanyu,2019,Drama,India
86853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,Sokagin Çocuklari,2019,"Drama, Family",Turkey
86854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,La vida sense la Sara Amat,2019,Drama,Spain