In [2]:
import pandas as pd 
import numpy as np

In [50]:
stats=pd.read_csv('1customers-100.csv')

In [51]:
stats

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [8]:
# ATTIBUTES

In [10]:
stats.shape

(100, 12)

In [11]:
stats.index

RangeIndex(start=0, stop=100, step=1)

In [14]:
stats.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [16]:
stats.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [17]:


# METHODS

In [19]:
# showing the info of the dataframe 
stats.info

<bound method DataFrame.info of     Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]>

In [20]:
stats.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [21]:



# FUNCTIONS

In [22]:
# number of rows 
len(stats)

100

In [23]:
max(stats)

'Website'

In [24]:
max(stats.index)

99

In [25]:
min(stats.index)

0

In [26]:
type(stats)

pandas.core.frame.DataFrame

In [28]:
round(stats,2)# rounding the values of the datasheet

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [31]:

#selecting one column

#1.1 syntax1

In [33]:
#selecting a column with [ ](preferred)
stats['Customer Id']

0     DD37Cf93aecA6Dc
1     1Ef7b82A4CAAD10
2     6F94879bDAfE5a6
3     5Cef8BFA16c5e3c
4     053d585Ab6b3159
           ...
95    cb8E23e48d22Eae
96    CeD220bdAaCfaDf
97    28CDbC0dFe4b1Db
98    c23d1D9EE8DEB0A
99    2354a0E336A91A1
Name: Customer Id, Length: 100, dtype: object

In [34]:
# check out the data type
type(stats['Customer Id'])

pandas.core.series.Series

In [38]:
# series : attributes and methods
stats['Customer Id'].index
stats['Customer Id'].head()

0    DD37Cf93aecA6Dc
1    1Ef7b82A4CAAD10
2    6F94879bDAfE5a6
3    5Cef8BFA16c5e3c
4    053d585Ab6b3159
Name: Customer Id, dtype: object

In [42]:
# syntax 2 
# selecting a column with . 

stats.City

0          East Leonard
1     East Jimmychester
2         Isabelborough
3            Bensonview
4        West Priscilla
            ...
95         East Richard
96         New Bradview
97           Ortegaland
98      Lake Elijahview
99            Judymouth
Name: City, Length: 100, dtype: object

In [45]:
# selecting with . (pitfalls)
stats['Customer Id']

0     DD37Cf93aecA6Dc
1     1Ef7b82A4CAAD10
2     6F94879bDAfE5a6
3     5Cef8BFA16c5e3c
4     053d585Ab6b3159
           ...
95    cb8E23e48d22Eae
96    CeD220bdAaCfaDf
97    28CDbC0dFe4b1Db
98    c23d1D9EE8DEB0A
99    2354a0E336A91A1
Name: Customer Id, Length: 100, dtype: object

In [46]:


# selecting two or more columns

In [12]:
report=pd.read_csv('file.csv')

In [58]:
report

    Unnamed: 0       Student Name Exam Name        Date  Points
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0
2          NaN         kelly frye   Biology  05/06/2016    81.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
10         NaN                NaN       NaN         NaN     NaN
11         NaN                NaN       NaN         NaN     NaN
12         NaN         21/06/2025       NaN         NaN     NaN

In [59]:
report[['Student Name','Points']]# selecting two columns

         Student Name  Points
0       Vaibhav Kumar   100.0
1       Velma Clemons    43.0
2          kelly frye    81.0
3         Louis Mcgee    11.0
4        Phyllis Paul    18.0
5      Zenaida Decker    55.0
6     Gillian Tillman    38.0
7     Constance Boone    16.0
8   Giselle Lancaster    73.0
9    Kirsten Mcdowell    16.0
10                NaN     NaN
11                NaN     NaN
12         21/06/2025     NaN

In [60]:
report.Points# only one column can be selected using .

0     100.0
1      43.0
2      81.0
3      11.0
4      18.0
5      55.0
6      38.0
7      16.0
8      73.0
9      16.0
10      NaN
11      NaN
12      NaN
Name: Points, dtype: float64

In [61]:


# Adding a new column

In [72]:
report['status']="passed"

In [13]:
report

    Unnamed: 0       Student Name Exam Name        Date  Points
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0
2          NaN         kelly frye   Biology  05/06/2016    81.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
10         NaN                NaN       NaN         NaN     NaN
11         NaN                NaN       NaN         NaN     NaN
12         NaN         21/06/2025       NaN         NaN     NaN

In [74]:
report.status

0     passed
1     passed
2     passed
3     passed
4     passed
5     passed
6     passed
7     passed
8     passed
9     passed
10    passed
11    passed
12    passed
Name: status, dtype: object

In [21]:
# creating random integer numbers between 1 and 100
score =np.random .randint(1,100,size =13)

In [16]:
# min value inclusive and high value exclusive 

min(score )
max (score )

88

In [22]:
# adding a new column to dataframe with an array 
report['score']=score
report

    Unnamed: 0       Student Name Exam Name        Date  Points  score
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0     83
1          NaN      Velma Clemons   Biology  05/06/2016    43.0     10
2          NaN         kelly frye   Biology  05/06/2016    81.0     89
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0     22
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0     65
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0     72
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0     91
7          NaN    Constance Boone   Biology  05/06/2016    16.0     95
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0     26
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0     37
10         NaN                NaN       NaN         NaN     NaN     45
11         NaN                NaN       NaN         NaN     NaN      6
12         NaN         21/06/2025       NaN         NaN     NaN     58