In [166]:
import numpy as np
import pandas as pd

In [167]:
lap=pd.read_csv('laptops.csv',encoding ='latin1')

In [168]:
lap.head(1)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros)
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"

In [173]:
 lap['Price (Euros)'] = lap['Price (Euros)'].str.replace(',', '.')
lap.head(1)
print(lap.columns)

Index(['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen',
       'CPU', 'RAM', ' Storage', 'GPU', 'Operating System',
       'Operating System Version', 'Weight', 'Price (Euros)'],
      dtype='object')

In [177]:
lap.drop('price (Euros)',axis=1)# delating a column

KeyError: "['price (Euros)'] not found in axis"

In [161]:
lap['price']=pd.to_numeric(lap['price'],errors='coerce')

TypeError: arg must be a list, tuple, 1-d array, or Series

In [147]:

lap['Screen Size']=lap['Screen Size'].str.replace('"','')

AttributeError: Can only use .str accessor with string values!

In [ ]:
# exercise 1 
#creating an array based on screen size 

lap['Screen Size']=pd.to_numeric(lap['Screen Size'])

In [148]:
np.where(lap['Screen Size']>14,'big' ,'smol' )

array(['smol', 'smol', 'big', ..., 'smol', 'big', 'big'], dtype='<U4')

In [149]:
lap['Size']=lap['Screen Size']>14

In [150]:
lap['Size'] =np.where(lap['Screen Size']>14,'big' ,'smol' )# assigning it to a new column

In [151]:
lap.head(5)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price,Size,price (Euros),Price (Euros)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69,smol,1339.69,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,898.94,smol,898.94,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,575.00,big,575.00,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,2537.45,big,2537.45,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,1803.60,smol,1803.60,1803.60

In [152]:

# exercise 2
# counting the numbers of smol
lap.value_counts('Size')

Size
big     840
smol    463
Name: count, dtype: int64

In [153]:

# filtering dataframe based on a condition
# find hp laptop which costs more than 2000

In [154]:
# Price (Euros)
lap=lap.rename(columns={'Price (Euros)':'price'})

In [155]:
lap.head(1)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price,Size,price (Euros),price
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69,smol,1339.69,1339.69

In [156]:
print(lap.columns)

Index(['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen',
       'CPU', 'RAM', ' Storage', 'GPU', 'Operating System',
       'Operating System Version', 'Weight', 'price', 'Size', 'price (Euros)',
       'price'],
      dtype='object')

In [157]:
lap.drop('price (Euros)',axis=1,inplace=True)# delating a column

In [158]:
lap.head(5)

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,price,Size,price
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,1339.69,smol,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,898.94,smol,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,575.00,big,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,2537.45,big,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,1803.60,smol,1803.60

In [159]:


# FILTERING DATAFRAME BASED ON MULTIPLE CONDITIONS

In [160]:

(lap['Manufacturer']=='Apple')& (lap['price']>1000)

TypeError: '>' not supported between instances of 'str' and 'int'