In [65]:
import numpy as np
import pandas as pd

In [66]:
report=pd.read_csv('file.csv')

In [67]:
report

    Unnamed: 0       Student Name Exam Name        Date  Points
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0
2          NaN         kelly frye   Biology  05/06/2016    81.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
10         NaN                NaN       NaN         NaN     NaN
11         NaN                NaN       NaN         NaN     NaN
12         NaN         21/06/2025       NaN         NaN     NaN

In [5]:
# create index

In [68]:
import random

In [69]:
# creating non repeetitive values for the index
ind=np.arange(0,13)

In [70]:
ind

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
# shuffling the indexes
random.shuffle(ind)

In [72]:
ind

array([ 7,  4,  8,  3,  2,  5,  1,  9,  6,  0, 10, 12, 11])

In [73]:
# creating a new column
report['ind']=ind
report

    Unnamed: 0       Student Name Exam Name        Date  Points  ind
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0    7
1          NaN      Velma Clemons   Biology  05/06/2016    43.0    4
2          NaN         kelly frye   Biology  05/06/2016    81.0    8
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0    3
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0    2
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0    5
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0    1
7          NaN    Constance Boone   Biology  05/06/2016    16.0    9
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0    6
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0    0
10         NaN                NaN       NaN         NaN     NaN   10
11         NaN                NaN       NaN         NaN     NaN   12
12         NaN         21/06/2025       NaN         NaN     NaN   11

In [79]:
 # set index
report.set_index('ind', inplace=True)

In [80]:
report.sort_values('ind',ascending=True,inplace=True)

In [81]:
report

     Unnamed: 0       Student Name Exam Name        Date  Points
ind
0           NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
1           NaN    Gillian Tillman   Biology  05/06/2016    38.0
2           NaN       Phyllis Paul   Biology  05/06/2016    18.0
3           NaN        Louis Mcgee   Biology  05/06/2016    11.0
4           NaN      Velma Clemons   Biology  05/06/2016    43.0
5           NaN     Zenaida Decker   Biology  05/06/2016    55.0
6           NaN  Giselle Lancaster   Biology  05/06/2016    73.0
7           NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
8           NaN         kelly frye   Biology  05/06/2016    81.0
9           NaN    Constance Boone   Biology  05/06/2016    16.0
10          NaN                NaN       NaN         NaN     NaN
11          NaN         21/06/2025       NaN         NaN     NaN
12          NaN                NaN       NaN         NaN     NaN

In [83]:


# Rename column

In [89]:
report.rename(columns={'Unnamed: 0':'Gender'},inplace =True)

In [90]:
report

     Gender       Student Name Exam Name        Date  Points
ind
0       NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
1       NaN    Gillian Tillman   Biology  05/06/2016    38.0
2       NaN       Phyllis Paul   Biology  05/06/2016    18.0
3       NaN        Louis Mcgee   Biology  05/06/2016    11.0
4       NaN      Velma Clemons   Biology  05/06/2016    43.0
5       NaN     Zenaida Decker   Biology  05/06/2016    55.0
6       NaN  Giselle Lancaster   Biology  05/06/2016    73.0
7       NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
8       NaN         kelly frye   Biology  05/06/2016    81.0
9       NaN    Constance Boone   Biology  05/06/2016    16.0
10      NaN                NaN       NaN         NaN     NaN
11      NaN         21/06/2025       NaN         NaN     NaN
12      NaN                NaN       NaN         NaN     NaN

In [91]:
report.rename(columns={'Unnamed: 0':'Gender','Student Name':'Name'},inplace =True)

In [92]:
report

     Gender               Name Exam Name        Date  Points
ind
0       NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
1       NaN    Gillian Tillman   Biology  05/06/2016    38.0
2       NaN       Phyllis Paul   Biology  05/06/2016    18.0
3       NaN        Louis Mcgee   Biology  05/06/2016    11.0
4       NaN      Velma Clemons   Biology  05/06/2016    43.0
5       NaN     Zenaida Decker   Biology  05/06/2016    55.0
6       NaN  Giselle Lancaster   Biology  05/06/2016    73.0
7       NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
8       NaN         kelly frye   Biology  05/06/2016    81.0
9       NaN    Constance Boone   Biology  05/06/2016    16.0
10      NaN                NaN       NaN         NaN     NaN
11      NaN         21/06/2025       NaN         NaN     NaN
12      NaN                NaN       NaN         NaN     NaN

In [97]:
# rename method
report.rename(index={0:'a'})

     Gender               Name Exam Name        Date  Points
ind
a       NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
1       NaN    Gillian Tillman   Biology  05/06/2016    38.0
2       NaN       Phyllis Paul   Biology  05/06/2016    18.0
3       NaN        Louis Mcgee   Biology  05/06/2016    11.0
4       NaN      Velma Clemons   Biology  05/06/2016    43.0
5       NaN     Zenaida Decker   Biology  05/06/2016    55.0
6       NaN  Giselle Lancaster   Biology  05/06/2016    73.0
7       NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
8       NaN         kelly frye   Biology  05/06/2016    81.0
9       NaN    Constance Boone   Biology  05/06/2016    16.0
10      NaN                NaN       NaN         NaN     NaN
11      NaN         21/06/2025       NaN         NaN     NaN
12      NaN                NaN       NaN         NaN     NaN