In [7]:
import pandas as pd

In [8]:
report =pd.read_csv('file.csv')


report.head()# to read first five rows

   Unnamed: 0   Student Name Exam Name        Date  Points
0         NaN  Vaibhav Kumar   Biology  05/06/2016   100.0
1         NaN  Velma Clemons   Biology  05/06/2016    43.0
2         NaN     kelly frye   Biology  05/06/2016    81.0
3         NaN    Louis Mcgee   Biology  05/06/2016    11.0
4         NaN   Phyllis Paul   Biology  05/06/2016    18.0

In [6]:
# adding a new column

In [24]:
# using  assign method 

# when to use ?  
# add multiple columns in a single line of code 
# when you need to overwrite the values of an existing columns (best practice )

# it returns a new object (a copy ) with all the original columns in addition to the new ones

In [9]:
import numpy as np

In [32]:
# creating a random numbers for our new score columns 
score1 =np.random.randint (1,100,size =13)
score2 =np.random.randint (1,100,size =13)

In [40]:
# creating a series using the random numbers 

series1 =pd.Series(score1,index=np.arange(0,13))
series2 =pd.Series(score2,index=np.arange(0,13))

In [41]:
# using assign() to add multiple columns
report=report.assign(score1=series1,score2=series2)

In [42]:
# show dataframe 
series1

0     73
1      5
2     90
3     54
4     98
5     78
6     38
7      3
8     85
9     59
10    92
11    80
12    42
dtype: int32

In [43]:
report

,test1,Unnamed: 0,Student Name,Exam Name,Date,Points,score1,score2
0,87,NaN,Vaibhav Kumar,Biology,05/06/2016,100.0,73,96
1,9,NaN,Velma Clemons,Biology,05/06/2016,43.0,5,97
2,36,NaN,kelly frye,Biology,05/06/2016,81.0,90,60
3,14,NaN,Louis Mcgee,Biology,05/06/2016,11.0,54,6
4,55,NaN,Phyllis Paul,Biology,05/06/2016,18.0,98,36
5,18,NaN,Zenaida Decker,Biology,05/06/2016,55.0,78,5
6,75,NaN,Gillian Tillman,Biology,05/06/2016,38.0,38,10
7,68,NaN,Constance Boone,Biology,05/06/2016,16.0,3,19
8,89,NaN,Giselle Lancaster,Biology,05/06/2016,73.0,85,89
9,71,NaN,Kirsten Mcdowell,Biology,05/06/2016,16.0,59,83
10,71,NaN,NaN,NaN,NaN,NaN,92,44
11,40,NaN,NaN,NaN,NaN,NaN,80,85
12,26,NaN,21/06/2025,NaN,NaN,NaN,42,94

In [37]:
# using insert method to  add a column at a specific position

In [44]:
# report.insert(0,'test1',series1)

ValueError: cannot insert test1, already exists

In [39]:

# math operations
#  operations in columns

In [45]:

# selecting a column and calculate total sum
report['score1'].sum()

797

In [46]:
# to count the rows 
report['score1'].count()

13

In [47]:
report['score1'].mean()

61.30769230769231

In [38]:
report['score1'].min()

8

In [39]:
report['score1'].max()

96

In [40]:
report['score1'].std()

27.837670474303295

In [48]:
report.describe()

           test1  Unnamed: 0      Points     score1     score2
count  13.000000         0.0   10.000000  13.000000  13.000000
mean   50.692308         NaN   45.100000  61.307692  55.692308
std    28.303076         NaN   31.313646  31.600065  37.113305
min     9.000000         NaN   11.000000   3.000000   5.000000
25%    26.000000         NaN   16.500000  42.000000  19.000000
50%    55.000000         NaN   40.500000  73.000000  60.000000
75%    71.000000         NaN   68.500000  85.000000  89.000000
max    89.000000         NaN  100.000000  98.000000  97.000000

In [44]:

# operations in rows

In [24]:
report['score1']+report['score2'].sum()

0     715
1     637
2     664
3     642
4     683
5     646
6     703
7     696
8     717
9     699
10    699
11    668
12    654
Name: score1, dtype: int32

In [46]:
# calculating the average score and assigning the result to a new column

In [49]:
report['avg']=report['score1']+report['score2'].sum()

In [56]:
report
report

,test1,Unnamed: 0,Student Name,Exam Name,Date,Points,score1,score2,avg,ravg
0,87,NaN,Vaibhav Kumar,Biology,05/06/2016,100.0,73,96,797,966
1,9,NaN,Velma Clemons,Biology,05/06/2016,43.0,5,97,729,831
2,36,NaN,kelly frye,Biology,05/06/2016,81.0,90,60,814,964
3,14,NaN,Louis Mcgee,Biology,05/06/2016,11.0,54,6,778,838
4,55,NaN,Phyllis Paul,Biology,05/06/2016,18.0,98,36,822,956
5,18,NaN,Zenaida Decker,Biology,05/06/2016,55.0,78,5,802,885
6,75,NaN,Gillian Tillman,Biology,05/06/2016,38.0,38,10,762,810
7,68,NaN,Constance Boone,Biology,05/06/2016,16.0,3,19,727,749
8,89,NaN,Giselle Lancaster,Biology,05/06/2016,73.0,85,89,809,983
9,71,NaN,Kirsten Mcdowell,Biology,05/06/2016,16.0,59,83,783,925
10,71,NaN,NaN,NaN,NaN,NaN,92,44,816,952
11,40,NaN,NaN,NaN,NaN,NaN,80,85,804,969
12,26,NaN,21/06/2025,NaN,NaN,NaN,42,94,766,902

In [57]:
# value counts 
report

,test1,Unnamed: 0,Student Name,Exam Name,Date,Points,score1,score2,avg,ravg
0,87,NaN,Vaibhav Kumar,Biology,05/06/2016,100.0,73,96,797,966
1,9,NaN,Velma Clemons,Biology,05/06/2016,43.0,5,97,729,831
2,36,NaN,kelly frye,Biology,05/06/2016,81.0,90,60,814,964
3,14,NaN,Louis Mcgee,Biology,05/06/2016,11.0,54,6,778,838
4,55,NaN,Phyllis Paul,Biology,05/06/2016,18.0,98,36,822,956
5,18,NaN,Zenaida Decker,Biology,05/06/2016,55.0,78,5,802,885
6,75,NaN,Gillian Tillman,Biology,05/06/2016,38.0,38,10,762,810
7,68,NaN,Constance Boone,Biology,05/06/2016,16.0,3,19,727,749
8,89,NaN,Giselle Lancaster,Biology,05/06/2016,73.0,85,89,809,983
9,71,NaN,Kirsten Mcdowell,Biology,05/06/2016,16.0,59,83,783,925
10,71,NaN,NaN,NaN,NaN,NaN,92,44,816,952
11,40,NaN,NaN,NaN,NaN,NaN,80,85,804,969
12,26,NaN,21/06/2025,NaN,NaN,NaN,42,94,766,902

In [10]:
# counting student name elemnts 
# len function
len (report['Student Name'])

13

In [2]:


# operations in rows

In [58]:
# calculating the sum in a row 
# report['ravg']=report['score1']+report['score2']+report['avg']
report

,test1,Unnamed: 0,Student Name,Exam Name,Date,Points,score1,score2,avg,ravg
0,87,NaN,Vaibhav Kumar,Biology,05/06/2016,100.0,73,96,797,966
1,9,NaN,Velma Clemons,Biology,05/06/2016,43.0,5,97,729,831
2,36,NaN,kelly frye,Biology,05/06/2016,81.0,90,60,814,964
3,14,NaN,Louis Mcgee,Biology,05/06/2016,11.0,54,6,778,838
4,55,NaN,Phyllis Paul,Biology,05/06/2016,18.0,98,36,822,956
5,18,NaN,Zenaida Decker,Biology,05/06/2016,55.0,78,5,802,885
6,75,NaN,Gillian Tillman,Biology,05/06/2016,38.0,38,10,762,810
7,68,NaN,Constance Boone,Biology,05/06/2016,16.0,3,19,727,749
8,89,NaN,Giselle Lancaster,Biology,05/06/2016,73.0,85,89,809,983
9,71,NaN,Kirsten Mcdowell,Biology,05/06/2016,16.0,59,83,783,925
10,71,NaN,NaN,NaN,NaN,NaN,92,44,816,952
11,40,NaN,NaN,NaN,NaN,NaN,80,85,804,969
12,26,NaN,21/06/2025,NaN,NaN,NaN,42,94,766,902

report

In [2]:
# sort by one column
report.sort_values(by='score1')

NameError: name 'report' is not defined