In [1]:
import pandas as pd
import numpy as np

In [2]:
report=pd.read_csv('file.csv')

In [3]:
report

    Unnamed: 0       Student Name Exam Name        Date  Points
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0
2          NaN         kelly frye   Biology  05/06/2016    81.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0
10         NaN                NaN       NaN         NaN     NaN
11         NaN                NaN       NaN         NaN     NaN
12         NaN         21/06/2025       NaN         NaN     NaN

In [12]:
maths=np.random.randint(0,100,size=10)

In [13]:
maths

array([89, 83, 48, 36, 98, 97, 19, 31, 42, 78])

In [14]:
s=pd.Series(maths,index=np.arange(0,10))

In [16]:
report=report.assign(maths=s)

In [17]:
report

    Unnamed: 0       Student Name Exam Name        Date  Points  maths
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0   89.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0   83.0
2          NaN         kelly frye   Biology  05/06/2016    81.0   48.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0   36.0
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0   98.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0   97.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0   19.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0   31.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0   42.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0   78.0
10         NaN                NaN       NaN         NaN     NaN    NaN
11         NaN                NaN       NaN         NaN     NaN    NaN
12         NaN         21/06/2025       NaN         NaN     NaN    NaN

In [18]:
# sortin one column 
report.sort_values(by='maths')

    Unnamed: 0       Student Name Exam Name        Date  Points  maths
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0   19.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0   31.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0   36.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0   42.0
2          NaN         kelly frye   Biology  05/06/2016    81.0   48.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0   78.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0   83.0
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0   89.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0   97.0
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0   98.0
10         NaN                NaN       NaN         NaN     NaN    NaN
11         NaN                NaN       NaN         NaN     NaN    NaN
12         NaN         21/06/2025       NaN         NaN     NaN    NaN

In [20]:
report.sort_values(by='maths',ascending=False)

    Unnamed: 0       Student Name Exam Name        Date  Points  maths
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0   98.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0   97.0
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0   89.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0   83.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0   78.0
2          NaN         kelly frye   Biology  05/06/2016    81.0   48.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0   42.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0   36.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0   31.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0   19.0
10         NaN                NaN       NaN         NaN     NaN    NaN
11         NaN                NaN       NaN         NaN     NaN    NaN
12         NaN         21/06/2025       NaN         NaN     NaN    NaN

In [23]:
# sort descending by multiple columns
report.sort_values(['maths','Points'],ascending=False)# it creates a copy

    Unnamed: 0       Student Name Exam Name        Date  Points  maths
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0   98.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0   97.0
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0   89.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0   83.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0   78.0
2          NaN         kelly frye   Biology  05/06/2016    81.0   48.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0   42.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0   36.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0   31.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0   19.0
10         NaN                NaN       NaN         NaN     NaN    NaN
11         NaN                NaN       NaN         NaN     NaN    NaN
12         NaN         21/06/2025       NaN         NaN     NaN    NaN

In [24]:
# it overides the values 
report.sort_values(['maths','Points'],ascending=False,inplace=True)

In [25]:
report

    Unnamed: 0       Student Name Exam Name        Date  Points  maths
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0   98.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0   97.0
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0   89.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0   83.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0   78.0
2          NaN         kelly frye   Biology  05/06/2016    81.0   48.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0   42.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0   36.0
7          NaN    Constance Boone   Biology  05/06/2016    16.0   31.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0   19.0
10         NaN                NaN       NaN         NaN     NaN    NaN
11         NaN                NaN       NaN         NaN     NaN    NaN
12         NaN         21/06/2025       NaN         NaN     NaN    NaN

In [26]:
report.sort_values ('Student Name',ascending =True,key=lambda col:col.str.lower())

    Unnamed: 0       Student Name Exam Name        Date  Points  maths
12         NaN         21/06/2025       NaN         NaN     NaN    NaN
7          NaN    Constance Boone   Biology  05/06/2016    16.0   31.0
6          NaN    Gillian Tillman   Biology  05/06/2016    38.0   19.0
8          NaN  Giselle Lancaster   Biology  05/06/2016    73.0   42.0
2          NaN         kelly frye   Biology  05/06/2016    81.0   48.0
9          NaN   Kirsten Mcdowell   Biology  05/06/2016    16.0   78.0
3          NaN        Louis Mcgee   Biology  05/06/2016    11.0   36.0
4          NaN       Phyllis Paul   Biology  05/06/2016    18.0   98.0
0          NaN      Vaibhav Kumar   Biology  05/06/2016   100.0   89.0
1          NaN      Velma Clemons   Biology  05/06/2016    43.0   83.0
5          NaN     Zenaida Decker   Biology  05/06/2016    55.0   97.0
10         NaN                NaN       NaN         NaN     NaN    NaN
11         NaN                NaN       NaN         NaN     NaN    NaN