In [1]:
import pandas as pd 
import numpy as np

df=pd.read_csv('file.csv')
del df['Unnamed: 0']
df=df.set_index('Student Name')
import random 
point1=[random.randint(150,180)for _ in range(13)]
df.rename(columns={'Points':'Marks'},inplace=True)
df['Height']=point1

df=df.dropna()# delete rows with any NaN values

1 Sample ()

In [3]:
df.head(3)

              Exam Name        Date  Marks  Height
Student Name
Vaibhav Kumar   Biology  05/06/2016  100.0     170
Velma Clemons   Biology  05/06/2016   43.0     169
kelly frye      Biology  05/06/2016   81.0     180

In [17]:
# extract 10 random elements from the 'Marks'column
df['Marks'].sample(5,random_state=99)

Student Name
Giselle Lancaster    73.0
Zenaida Decker       55.0
Phyllis Paul         18.0
kelly frye           81.0
Gillian Tillman      38.0
Name: Marks, dtype: float64

In [30]:
# extract a random 50% sample of the dataframe
# df.sample(int(10/2))
df.sample(frac=0.5,random_state=2)  # same as above

                Exam Name        Date  Marks  Height
Student Name
Phyllis Paul      Biology  05/06/2016   18.0     158
Velma Clemons     Biology  05/06/2016   43.0     169
Zenaida Decker    Biology  05/06/2016   55.0     159
Vaibhav Kumar     Biology  05/06/2016  100.0     170
Constance Boone   Biology  05/06/2016   16.0     178

In [32]:
# upsample : increase the sample rate -> frac>1 ( Note : replace parameter>1  )
df.sample(frac=2,replace=True,random_state=32)# doubles the rows

                  Exam Name        Date  Marks  Height
Student Name
Constance Boone     Biology  05/06/2016   16.0     178
Zenaida Decker      Biology  05/06/2016   55.0     159
Gillian Tillman     Biology  05/06/2016   38.0     156
Giselle Lancaster   Biology  05/06/2016   73.0     174
Louis Mcgee         Biology  05/06/2016   11.0     175
Constance Boone     Biology  05/06/2016   16.0     178
Kirsten Mcdowell    Biology  05/06/2016   16.0     162
Louis Mcgee         Biology  05/06/2016   11.0     175
Zenaida Decker      Biology  05/06/2016   55.0     159
Kirsten Mcdowell    Biology  05/06/2016   16.0     162
Phyllis Paul        Biology  05/06/2016   18.0     158
Velma Clemons       Biology  05/06/2016   43.0     169
Louis Mcgee         Biology  05/06/2016   11.0     175
Velma Clemons       Biology  05/06/2016   43.0     169
kelly frye          Biology  05/06/2016   81.0     180
Louis Mcgee         Biology  05/06/2016   11.0     175
Giselle Lancaster   Biology  05/06/2016   73.0     174
kelly frye          Biology  05/06/2016   81.0     180
Phyllis Paul        Biology  05/06/2016   18.0     158
kelly frye          Biology  05/06/2016   81.0     180