In [40]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
df=pd.read_csv('file.csv')

In [32]:
df

        Student Name Exam Name        Date  Points  height  Height
0      Vaibhav Kumar   Biology  05/06/2016   100.0     170     161
1      Velma Clemons   Biology  05/06/2016    43.0     163     161
2         kelly frye   Biology  05/06/2016    81.0     168     170
3        Louis Mcgee   Biology  05/06/2016    11.0     161     167
4       Phyllis Paul   Biology  05/06/2016    18.0     164     166
5     Zenaida Decker   Biology  05/06/2016    55.0     165     167
6    Gillian Tillman   Biology  05/06/2016    38.0     166     170
7    Constance Boone   Biology  05/06/2016    16.0     168     163
8  Giselle Lancaster   Biology  05/06/2016    73.0     161     166
9   Kirsten Mcdowell   Biology  05/06/2016    16.0     169     167

In [29]:
import random

height=[random.randint(160,170) for _ in range(10)]

In [33]:
df['Height']=height

C:\Users\vk\AppData\Local\Temp\ipykernel_15500\4018292841.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Height']=height

In [30]:
height

[161, 161, 170, 167, 166, 167, 170, 163, 166, 167]

In [41]:
df

        Student Name Exam Name        Date  Points  height
0      Vaibhav Kumar   Biology  05/06/2016   100.0     170
1      Velma Clemons   Biology  05/06/2016    43.0     163
2         kelly frye   Biology  05/06/2016    81.0     168
3        Louis Mcgee   Biology  05/06/2016    11.0     161
4       Phyllis Paul   Biology  05/06/2016    18.0     164
5     Zenaida Decker   Biology  05/06/2016    55.0     165
6    Gillian Tillman   Biology  05/06/2016    38.0     166
7    Constance Boone   Biology  05/06/2016    16.0     168
8  Giselle Lancaster   Biology  05/06/2016    73.0     161
9   Kirsten Mcdowell   Biology  05/06/2016    16.0     169

In [42]:
df.pivot(index='Student Name',columns='height' ,values='Points',)

height              161   163   164   165   166   168   169    170
Student Name
Constance Boone     NaN   NaN   NaN   NaN   NaN  16.0   NaN    NaN
Gillian Tillman     NaN   NaN   NaN   NaN  38.0   NaN   NaN    NaN
Giselle Lancaster  73.0   NaN   NaN   NaN   NaN   NaN   NaN    NaN
Kirsten Mcdowell    NaN   NaN   NaN   NaN   NaN   NaN  16.0    NaN
Louis Mcgee        11.0   NaN   NaN   NaN   NaN   NaN   NaN    NaN
Phyllis Paul        NaN   NaN  18.0   NaN   NaN   NaN   NaN    NaN
Vaibhav Kumar       NaN   NaN   NaN   NaN   NaN   NaN   NaN  100.0
Velma Clemons       NaN  43.0   NaN   NaN   NaN   NaN   NaN    NaN
Zenaida Decker      NaN   NaN   NaN  55.0   NaN   NaN   NaN    NaN
kelly frye          NaN   NaN   NaN   NaN   NaN  81.0   NaN    NaN